# Generated by Django 3.0.6 on 2020-07-04 21:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=300)),
                ('original_price', models.FloatField(null=True)),
                ('gender', models.CharField(choices=[('M', 'men'), ('F', 'women'), ('U', 'unisex')], max_length=1)),
                ('web_specific_id', models.CharField(max_length=300)),
                ('sale_price', models.FloatField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('CAD', 'CAD'), ('KRW', 'KRW')], max_length=3)),
                ('product_link', models.CharField(default=None, max_length=500, null=True)),
                ('product_image', models.CharField(default=None, max_length=500, null=True)),
                ('item_type', models.CharField(max_length=100, null=True)),
                ('data', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('link', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_data', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), size=None)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='associated_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Site'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Brand'),
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('CAD', 'CAD'), ('KRW', 'KRW')], max_length=3)),
                ('date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
            ],
        ),
    ]
