# Generated by Django 3.0.6 on 2020-08-02 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='data',
        ),
        migrations.RemoveField(
            model_name='product',
            name='item_type',
        ),
        migrations.AddField(
            model_name='brand',
            name='item_count',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='site',
            name='item_count',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='web_specific_id',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ACCESSORIES', 'ACCESSORIES'), ('BELTS', 'BELTS'), ('EYEWEAR', 'EYEWEAR'), ('HATS', 'HATS'), ('CAPS', 'CAPS'), ('BEANIES', 'BEANIES'), ('JEWELRY', 'JEWELRY'), ('BRACELETS', 'BRACELETS'), ('EARRINGS', 'EARRINGS'), ('NECKLACES', 'NECKLACES'), ('RINGS', 'RINGS'), ('BAGS', 'BAGS'), ('BACKPACKS', 'BACKPACKS'), ('BRIEFCASES', 'BRIEFCASES'), ('DUFFLE BAGS', 'DUFFLE BAGS'), ('MESSENGER BAGS', 'MESSENGER BAGS'), ('POUCHES', 'POUCHES'), ('TOTE BAGS', 'TOTE BAGS'), ('TRAVEL BAGS', 'TRAVEL BAGS'), ('CLOTHING', 'CLOTHING'), ('TOP', 'TOP'), ('JACKETS', 'JACKETS'), ('DENIM JACKETS', 'DENIM JACKETS'), ('LEATHER JACKETS', 'LEATHER JACKETS'), ('DOWN JACKETS', 'DOWN JACKETS'), ('FUR & SHEARLING', 'FUR & SHEARLING'), ('COATS', 'COATS'), ('PEA COATS', 'PEA COATS'), ('LONG COATS', 'LONG COATS'), ('TRENCH COATS', 'TRENCH COATS'), ('SHIRTS', 'SHIRTS'), ('SWEATERS', 'SWEATERS'), ('CARDIGANS', 'CARDIGANS'), ('CREWNECKS', 'CREWNECKS'), ('HOODIES', 'HOODIES'), ('SWEATSHIRTS', 'SWEATSHIRTS'), ('TURTLENECKS', 'TURTLENECKS'), ('V-NECKS', 'V-NECKS'), ('T-SHIRTS', 'T-SHIRTS'), ('TANK TOPS', 'TANK TOPS'), ('POLOS', 'POLOS'), ('BOTTOM', 'BOTTOM'), ('JEANS', 'JEANS'), ('SHORTS', 'SHORTS'), ('PANTS', 'PANTS'), ('CARGO PANTS', 'CARGO PANTS'), ('LEATHER_PANTS', 'LEATHER_PANTS'), ('SWEATPANTS', 'SWEATPANTS'), ('TROUSERS', 'TROUSERS'), ('SHOES', 'SHOES'), ('SNEAKERS', 'SNEAKERS'), ('BOOTS', 'BOOTS'), ('LACE UPS', 'LACE UPS'), ('LOAFERS', 'LOAFERS'), ('SANDALS', 'SANDALS')], max_length=100)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Category'),
        ),
    ]
